---
deployment:
  tasks:
    - export DEPLOYPATH=/home/vmksybel/it-lens.hu
    - if [ -f "dist/index.html" ]; then /bin/cp -rf dist/* $DEPLOYPATH/; fi
    - if [ -f "it-lens-web/dist/index.html" ]; then /bin/cp -rf it-lens-web/dist/* $DEPLOYPATH/; fi
    - if [ -f "index.html" ] && [ -d "_astro" ]; then /bin/cp -rf index.html _astro $DEPLOYPATH/; fi
